apiVersion: apps/v1
kind: Pod
metadata:
  name: development
spec:
  containers:
    - env:
        - name: GF_AUTH_ANONYMOUS_ENABLED
          value: 'true'
        - name: GF_LOG_LEVEL
          value: debug
        - name: GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS
          value: albertowd-oraclegrafana-datasource
      image: grafana/grafana:latest
      hostname: grafana
      name: grafana
      ports:
        - containerPort: 3000
          hostPort: 3000
      restartPolicy: Always
      volumeMounts:
        - name: oracle-grafana-plugin
          mountPath: /var/lib/grafana/plugins/awd-oraclegrafana-datasource

    - env:
        - name: ORACLE_PWD
          value: oracle_password
      image: container-registry.oracle.com/database/express:21.3.0-xe
      hostname: oracle
      name: oracle
      ports:
        - containerPort: 1521
          hostPort: 1521
      restartPolicy: Always
      volumeMounts:
        - name: oracle-example-database
          mountPath: /opt/oracle/scripts/startup

  volumes:
    - hostPath:
        path: ./dist/
        type: Directory
      name: oracle-grafana-plugin
    - hostPath:
        path: ./example/database/
        type: Directory
      name: oracle-example-database