name: Tag Release

on:
  push:
    branches:
      - 'relrease/*'
    tags:
      - '*'
  workflow_dispatch:

jobs:
  release-creation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: npm
          node-version: latest
      - uses: actions/setup-go@v4
        with:
          go-version: '>=1.20'
      - name: Make Release Files
        run: sh ./scripts/make-release.sh
      - name: Publish Release
        uses: softprops/action-gh-release@v0.1.15
        with:
          draft: true
          files: |
            albertowd-oraclegrafana-datasource-*.tar.gz
